# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('occ_data', models.CharField(max_length=1000)),
                ('c_data', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='refString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=1000)),
                ('save_date', models.DateTimeField(verbose_name='date created')),
                ('SA', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='letterdetails',
            name='refString',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FMsearch.refString'),
        ),
    ]
